version: '3.2'

services:
  # Java APP (Spring Boot)
  academy-srv:
    build:
      context: ..
      dockerfile: academy-srv.dockerfile
    image: logate/academy-srv:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/config
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: on-failure
    container_name: academy_srv
    networks:
      - academynet

  # MySQL 5.7.36
  academy-db:
    build:
      context: ..
      dockerfile: academy-db.dockerfile
    image: logate/academy-db:5.7.36
    ports:
      - "3307:3307"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    restart: on-failure
    container_name: academy_db
    networks:
      - academynet

networks:
  academynet: